### ISSUE TITLE
I can't use faker functions directly

### ISSUE THREAD

**Issue by stevenbarragan** [fabsrc/artillery-plugin-faker#1]
```yaml
config:
  target: "http://google.com"
  plugins:
    faker: {}
  phases:
    - duration: 1
      arrivalRate: 1
  variables:
    variableUuid: "$faker.random.uuid"
scenarios:
  - flow:
    - log: "Variable uuid {{ variableUuid }}"
    - log: "Random uuid: {{ $faker('random.uuid') }}"
```

output:
```bash
...
⠹ Variable uuid 1b78a833-2567-431b-9d1d-037063e9e91e
undefined
...
```
