### ISSUE TITLE
Not working with engine socketio 

### ISSUE THREAD

**Issue by ZebboKlaufix** [fabsrc/artillery-plugin-faker#19]
If I define socketio as the engine, like described by [artillery](https://www.artillery.io/docs/reference/engines/socketio), it seems to stop working. Instead it's prompting:
```
\ Making request with query: $faker.name.fullName
- Making request with query: $faker.name.fullName
/ Making request with query: $faker.name.fullName
/ Making request with query: $faker.name.fullName
| Making request with query: $faker.name.fullName
\ Making request with query: $faker.name.fullName
- Making request with query: $faker.name.fullName
/ Making request with query: $faker.name.fullName
| Making request with query: $faker.name.fullName
```

example script:

```
config:
  target: "http://127.0.0.1:5000"
  socketio:
    transports: ["websocket"]
  phases:
    - duration: 10
      arrivalRate: 1
  plugins:
    faker:
      locale: en
  variables:
    username: "$faker.name.fullName"

scenarios:
  - name: My Socket.IO test
    engine: socketio # Enable the Socket.IO engine
    flow:
      - log: "Making request with query: {{ username }}"
      - emit:
          channel: "join_room"
          data: "demo"
```

**Comment by fabsrc** [comment]
This is probably an issue with the Socket.IO engine (and maybe also the WS engine) in artillery. It seems like their own [fake-data plugin](https://www.npmjs.com/package/artillery-plugin-fake-data) also does not work.

I tested it with this config:

```yaml
config:
  target: "http://127.0.0.1:5000"
  socketio:
    transports: ["websocket"]
  phases:
    - duration: 10
      arrivalRate: 1
  plugins:
    fake-data: {}
    faker: {}
  variables:
    username: "$faker.name.fullName"

scenarios:
  - name: Socket.IO test
    engine: socketio
    flow:
      - log: "SOCKET IO: {{ $randFullName() }}"
      - log: "SOCKET IO: {{ username }}"
```

```
⠏ undefined
SOCKET IO: $faker.name.fullName
⠙ undefined
SOCKET IO: $faker.name.fullName
⠼ undefined
SOCKET IO: $faker.name.fullName
```

With the HTTP engine both plugins work correctly:

```yaml
config:
  target: "http://127.0.0.1:5000"
  socketio:
    transports: ["websocket"]
  phases:
    - duration: 10
      arrivalRate: 1
  plugins:
    fake-data: {}
    faker: {}
  variables:
    username: "$faker.name.fullName"

scenarios:
  - name: HTTP test
    engine: http
    flow:
      - log: "HTTP: {{ $randFullName() }}"
      - log: "HTTP: {{ username }}"
```

```
⠋ HTTP: Pablo Kristinsdóttir
HTTP: Jan DuBuque
⠹ HTTP: Victoria Ríos
HTTP: Mary Stanton
⠼ HTTP: Isah Gísladóttir
HTTP: Michelle Hoppe
```

So maybe it makes sense to create an [issue in the artillery repo](https://github.com/artilleryio/artillery/issues).
